services:
  postgres:
    image: postgres:15-alpine
    container_name: tbforum-postgres
    environment:
      POSTGRES_DB: tbforum_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pzc86497558

    ports:
      - "5432:5432"
    restart: unless-stopped